### ISSUE TITLE
tostring (v) 疑问

### ISSUE THREAD

**Issue by apppur** [cloudwu/lua53doc#19]
Receives a value of any type and converts it to a string in a human-readable format. Floats always produce strings with some floating-point indication (either a decimal dot or an exponent).
可以接收任何类型，它将其转换为人可阅读的字符串形式。 浮点数总被转换为小数点分割的形式（一定有小数点，没有指数）。
either a decimal dot or an exponent 翻译为："无论是小数点或指数" 是否更合适?

**Comment by cloudwu** [comment]
对，这个翻错了。我改过来，谢谢。
