### ISSUE TITLE
3.1 – 词法约定中的\z

### ISSUE THREAD

**Issue by czlc** [cloudwu/lua53doc#29]
转义串 '\z' 会忽略其后的一系列空白符，包括换行；但是实际测试却没有忽略换行，print("hello\z\nworld")，看代码似乎没有判断转义符？

**Comment by cloudwu** [comment]
你不觉得 print("hello\z\nworld") 这种写法下 \z 没有任何意义吗?
\z 要解决的问题是
print("hello\z
    world");
这种源代码排版问题.

文档里对 \z 的作用解释的很清楚了.

**Comment by czlc** [comment]
哦，明白了，不好意思：）
