### ISSUE TITLE
感觉 C API 节内第一行可以译为：简化了 C 当中的延续点 API

### ISSUE THREAD

**Issue by dashaomai** [cloudwu/lua53doc#3]
感觉 C API 节内第一行可以译为：简化了 C 当中的延续点 API；

原文是：simpler API for continuation functions in C
原译是：简化了延续点 API

**Comment by cloudwu** [comment]
这一节都是谈 C API 的，API 就是指 C 函数. 翻译不用逐字， 平时怎么写中文就怎么写。
