### ISSUE TITLE
yield 翻译

### ISSUE THREAD

**Issue by keyring** [cloudwu/lua53doc#39]
yield 翻译成 **让出**，读着很别扭啊。
翻译成 **暂停**、**休眠**或者**挂起**如何？

**Comment by cloudwu** [comment]
但是直译就是让出呀.

我觉得把, 这些就是读着读着就好了. 一开始 closure 被翻译成闭包, 我也是怎么都觉得别扭.

**Comment by keyring** [comment]
我觉得还是意译成**休眠**或者**挂起**吧。如果你没意见，我就提一个pr。

**Comment by cloudwu** [comment]
问题在于, 休眠一般对应 sleep, 挂起对应 suspend . 是不同的意思. 所以我才选择一个独立的词.
另外我认为让出是更准确的意译. 因为休眠通常指线程在调度器的安排下停止一段时间,挂起指调度器将线程从执行队列里移除, 都是指调度器对线程的动作. coroutine 的 yield 是协程的自主行为, 指它让出执行权.

**Comment by keyring** [comment]
原文中**a coroutine only suspends its execution by explicitly calling a yield function**，说明 yield 操作使协程 suspend，那直译为 **挂起** 操作使协程 **挂起** 执行并无不妥。再者，**挂起** 从来没有局限于**调度器操控线程**这个意思上。即使考虑到你说的这个通常意义（容易让人误解），要强调协程的主动性，那么换用**休眠**也是可行的。休眠与调度器无关，也具有保存当前状态的意义，更具备**主动性**（比如动物冬眠是动物的主动行为）。最后，相比协程**让出**执行权，协程**暂停**执行更符合他的行为，毕竟之后还可以从暂停点（休眠点唤醒）**继续**执行。

**Comment by cloudwu** [comment]
可是原文包括 api 的名字也没有用 suspend 而用了 yield 这个词啊。
“让出” 不是有更准确的中文含义吗？
我也不认为 "挂起" 和 "让出“ 从中文理解角度有什么差别，都是因为操作系统相关概念的引入而翻译成中文造出的词。反而“挂起” 更接近一个生造的词。　

那种别扭的感觉只不过是见的少而已，读多了就不别扭了。正如几年前，我觉得 coroutine 翻译成协程，closure 翻译成闭包，我也感觉无比别扭一样。

**Comment by keyring** [comment]
好吧，你赢了，说了半天的**让出**，我已经不觉得别扭了。。。。。但不是一个好的翻译。

**Comment by lushl9301** [comment]
It should be translated as **让出**. Really, if you have some OS course experiences, you will see **yield** a lot. One thread or process voluntarily gives CPU time to others.
