### ISSUE TITLE
71 行：可能和这里的版本有所不同。

### ISSUE THREAD

**Issue by dashaomai** [cloudwu/lua53doc#4]
原文是：which may differ slightly from the local copy distributed in this package.
译文是：可能和<A HREF="contents.html">这里的版本</A> 有所不同。

我感觉：可能与随当前软件包发布的<A HREF="contents.html">本地版本</A>略有不同。

**Comment by cloudwu** [comment]
"这里的版本" 就是指 “随当前软件包发布的本地版本” 啊。
这个翻译版是在线发布的， 所以不在某个发行包中。

**Comment by cloudwu** [comment]
谢谢。
总的来说，我不主张逐字翻译。明白作者想表达的意思后，准确的把原意用中文重新表达出来就可以了。
就这个地方，我做了略微的修改，是为了符合译本的环境。我觉得即使放在原文环境中，也是恰当的。

**Comment by cloudwu** [comment]
另外，其实不必摘录一行来提 issue, 以后你可以在 commit 里直接加 line comment :)

**Comment by dashaomai** [comment]
嗯嗯，好的没问题 :)
